[package]
name = "lunar_lander"
version = "0.1.0"
edition = "2021"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[dependencies]
bevy = { version = "0.8.1", features = ["dynamic"] }
bevy_rapier2d = "0.17.0"
bevy_prototype_debug_lines = "0.8"
bevy-inspector-egui = "0.12.1"
